name: Defect Report - Bug
description: Report a functional defect (behavior does not match specification)
title: "[BUG] "
labels: ["defect-bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Defect Report - BUG
        Use this template to report functional defects where implemented behavior does not match specification or user expectation.
        
        **Classification**: BUG (Functional Defect)
        
        This template follows the Defect Resolution and Maintenance Canon from maturion-foreman-governance.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this defect?
      options:
        - CRITICAL - Production down, data loss, security breach, blocking users
        - HIGH - Major functionality broken, significant user impact
        - MEDIUM - Functionality degraded, moderate user impact, workaround available
        - LOW - Minor issue, cosmetic, limited impact
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Defect Description
      description: Clear description of what is wrong
      placeholder: Describe the defect...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the defect
      placeholder: |
        1. Go to...
        2. Click on...
        3. Enter...
        4. Observe...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: Describe expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: Describe actual behavior...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: Who is affected and how?
      placeholder: |
        - Affected users: (all users / specific cohort / admin only)
        - Affected functionality: (core workflow / secondary feature / edge case)
        - Business impact: (revenue / reputation / compliance)
        - Frequency: (always / intermittent / rare)
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      description: Screenshots, logs, error messages
      placeholder: Paste screenshots, logs, or error messages here...

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Where was defect observed?
      placeholder: |
        - Environment: (production / staging / local)
        - Browser/Device: (if applicable)
        - Version: (if known)
        - Date/Time: (when discovered)
    validations:
      required: true

  - type: input
    id: discoverer
    attributes:
      label: Discovered By
      description: Who discovered this defect?
      placeholder: Name or username
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Is there a temporary workaround?
      placeholder: Describe any workaround if available...

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any other relevant information

  - type: checkboxes
    id: checklist
    attributes:
      label: Reporter Checklist
      options:
        - label: I have verified this defect is reproducible
          required: true
        - label: I have documented the impact
          required: true
        - label: I have assigned appropriate severity
          required: true
        - label: I have provided reproduction steps
          required: true
